/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rpsSol from "./RPS.sol";
export type { rpsSol };
import type * as rpsv2Sol from "./RPSV2.sol";
export type { rpsv2Sol };
export * as factories from "./factories";
export type { Hasher } from "./RPS.sol/Hasher";
export { Hasher__factory } from "./factories/RPS.sol/Hasher__factory";
export type { RPS } from "./RPS.sol/RPS";
export { RPS__factory } from "./factories/RPS.sol/RPS__factory";
export type { RPSV2 } from "./RPSV2.sol/RPSV2";
export { RPSV2__factory } from "./factories/RPSV2.sol/RPSV2__factory";
